In [14]:
import pandas as pd
import numpy as np                
from math import *
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [34]:
#Importing train and test data
train_df = pd.read_csv('ECG200_TRAIN.txt',delimiter='\s+', header=None)
test_df = pd.read_csv('ECG200_TEST.txt', delimiter='\s+',header=None)
train_df.head()


0         1         2         3         4         5         6         7   \
0 -1.0  0.502055  0.542163  0.722383  1.428885  2.136516  2.281149  1.936274   
1  1.0  0.147647  0.804668  0.367771  0.243894  0.026614 -0.274402  0.096731   
2 -1.0  0.316646  0.243199  0.370471  1.063738  1.678187  1.759558  1.697717   
3 -1.0  1.168874  2.075901  1.760140  1.606446  1.949046  1.302842  0.459332   
4  1.0  0.648658  0.752026  2.636231  3.455716  2.118157  0.520620 -0.188627   

         8         9   ...        87        88        89        90        91  \
0  1.468890  1.008845  ...  0.931043  0.610298  0.638894  0.684679  0.583238   
1 -0.747731 -1.609777  ... -0.533503 -0.400228  0.176084  1.111768  2.438428   
2  1.612159  1.168188  ...  0.764229  0.610621  0.552900  0.566786  0.604002   
3  0.516412  0.852180  ...  0.419006  0.723888  1.323947  2.136488  1.746597   
4  0.780818  0.933775  ... -0.097869 -0.136787 -0.340237 -0.089441 -0.080297   

         92        93        94        95        96  
0  0.640522  0.708585  0.705011  0.713815  0.433765  
1  2.734889  1.736054  0.036857 -1.265074 -0.208024  
2  0.777068  0.812345  0.748848  0.818042  0.539347  
3  1.470220  1.893512  1.256949  0.800407  0.731540  
4 -0.192584 -0.304704 -0.454556  0.314590  0.582190  

[5 rows x 97 columns]

In [16]:
#Creating train x and y and test x and y

train_x = train_df.drop(train_df.columns[0], axis = 1)
train_y = train_df.iloc[:,0]
test_x = test_df.drop(train_df.columns[0], axis = 1)
test_y = test_df.iloc[:,0]


In [17]:
#creating train and test matrix
train_matrix = np.matrix(train_df)
train_x_matrix = np.asmatrix(train_x)
test_x_matrix = np.asmatrix(test_x)
test_y_array = np.asarray(test_y)


In [18]:
def Minkowski_distance(R1, R2, p,length):
    distance = 0.0
    for i in length:
        distance += (abs(R1[i]-R2[i]))**p        
    return distance**(1/p)
  

In [19]:
def get_neighbors(train, test, k, p):
    distances = list()
    length = range(len(test)-1)
    for train_row in train:
        dist = Minkowski_distance(test, train_row,p,length)
        distances.append((train_row, dist))
        distances.sort(key=lambda tup: tup[1])
        neighbors = list()
    for i in range(k):
        neighbors.append(distances[i][0])
    return neighbors


In [20]:
def predict_classification(train, test, k,p):
    neighbors = get_neighbors(train, test, k, p)
    output_values = [row[0] for row in neighbors]
    prediction = max(set(output_values), key=output_values.count)
    return prediction

# kNN Algorithm
def k_nearest_neighbors(train, test, k, p):
    predictions = list()
    for row in test:
        output = predict_classification(train, row, k,p)
        predictions.append(output)
    return(predictions)


In [21]:

prediction1 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),3,0.5)) # k = 3, p = 0.5
prediction2 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),5,0.5)) # k = 5 , p = 0.5
prediction3 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),11,0.5))# k = 11 , p = 0.5

prediction4 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),3,1)) # k = 3, p = 1
prediction5 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),5,1)) # k = 5 , p = 1
prediction6 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),11,1))# k = 11 , p = 1

prediction7 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),3,2)) # k = 3, p = 2
prediction8 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),5,2)) # k = 5 , p = 2
prediction9 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),11,2))# k = 11 , p = 2

prediction10 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),3,4)) # k = 3, p = 4
prediction11 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),5,4)) # k = 5 , p = 4
prediction12 = np.asarray(k_nearest_neighbors(np.asarray(train_matrix),np.asarray(test_x_matrix),11,4))# k = 11 , p = 4


In [22]:
print(confusion_matrix(test_y_array,prediction1))
print(classification_report(test_y_array,prediction1))

[[29  7]
 [ 2 62]]
              precision    recall  f1-score   support

        -1.0       0.94      0.81      0.87        36
         1.0       0.90      0.97      0.93        64

    accuracy                           0.91       100
   macro avg       0.92      0.89      0.90       100
weighted avg       0.91      0.91      0.91       100



In [23]:
print(confusion_matrix(test_y_array,prediction2))
print(classification_report(test_y_array,prediction2))

[[25 11]
 [ 3 61]]
              precision    recall  f1-score   support

        -1.0       0.89      0.69      0.78        36
         1.0       0.85      0.95      0.90        64

    accuracy                           0.86       100
   macro avg       0.87      0.82      0.84       100
weighted avg       0.86      0.86      0.86       100



In [24]:
print(confusion_matrix(test_y_array,prediction3))
print(classification_report(test_y_array,prediction3))

[[28  8]
 [11 53]]
              precision    recall  f1-score   support

        -1.0       0.72      0.78      0.75        36
         1.0       0.87      0.83      0.85        64

    accuracy                           0.81       100
   macro avg       0.79      0.80      0.80       100
weighted avg       0.81      0.81      0.81       100



In [25]:
print(confusion_matrix(test_y_array,prediction4))
print(classification_report(test_y_array,prediction4))

[[28  8]
 [ 1 63]]
              precision    recall  f1-score   support

        -1.0       0.97      0.78      0.86        36
         1.0       0.89      0.98      0.93        64

    accuracy                           0.91       100
   macro avg       0.93      0.88      0.90       100
weighted avg       0.92      0.91      0.91       100



In [26]:
print(confusion_matrix(test_y_array,prediction5))
print(classification_report(test_y_array,prediction5))

[[25 11]
 [ 2 62]]
              precision    recall  f1-score   support

        -1.0       0.93      0.69      0.79        36
         1.0       0.85      0.97      0.91        64

    accuracy                           0.87       100
   macro avg       0.89      0.83      0.85       100
weighted avg       0.88      0.87      0.86       100



In [27]:
print(confusion_matrix(test_y_array,prediction6))
print(classification_report(test_y_array,prediction6))

[[27  9]
 [ 7 57]]
              precision    recall  f1-score   support

        -1.0       0.79      0.75      0.77        36
         1.0       0.86      0.89      0.88        64

    accuracy                           0.84       100
   macro avg       0.83      0.82      0.82       100
weighted avg       0.84      0.84      0.84       100



In [28]:
print(confusion_matrix(test_y_array,prediction7))
print(classification_report(test_y_array,prediction7))

[[25 11]
 [ 1 63]]
              precision    recall  f1-score   support

        -1.0       0.96      0.69      0.81        36
         1.0       0.85      0.98      0.91        64

    accuracy                           0.88       100
   macro avg       0.91      0.84      0.86       100
weighted avg       0.89      0.88      0.87       100



In [29]:
print(confusion_matrix(test_y_array,prediction8))
print(classification_report(test_y_array,prediction8))

[[23 13]
 [ 2 62]]
              precision    recall  f1-score   support

        -1.0       0.92      0.64      0.75        36
         1.0       0.83      0.97      0.89        64

    accuracy                           0.85       100
   macro avg       0.87      0.80      0.82       100
weighted avg       0.86      0.85      0.84       100



In [30]:
print(confusion_matrix(test_y_array,prediction9))
print(classification_report(test_y_array,prediction9))

[[23 13]
 [ 5 59]]
              precision    recall  f1-score   support

        -1.0       0.82      0.64      0.72        36
         1.0       0.82      0.92      0.87        64

    accuracy                           0.82       100
   macro avg       0.82      0.78      0.79       100
weighted avg       0.82      0.82      0.81       100



In [31]:
print(confusion_matrix(test_y_array,prediction10))
print(classification_report(test_y_array,prediction10))

[[10 26]
 [ 0 64]]
              precision    recall  f1-score   support

        -1.0       1.00      0.28      0.43        36
         1.0       0.71      1.00      0.83        64

    accuracy                           0.74       100
   macro avg       0.86      0.64      0.63       100
weighted avg       0.82      0.74      0.69       100



In [32]:
print(confusion_matrix(test_y_array,prediction11))
print(classification_report(test_y_array,prediction11))

[[13 23]
 [ 1 63]]
              precision    recall  f1-score   support

        -1.0       0.93      0.36      0.52        36
         1.0       0.73      0.98      0.84        64

    accuracy                           0.76       100
   macro avg       0.83      0.67      0.68       100
weighted avg       0.80      0.76      0.72       100



In [33]:
print(confusion_matrix(test_y_array,prediction12))
print(classification_report(test_y_array,prediction12))

[[13 23]
 [ 3 61]]
              precision    recall  f1-score   support

        -1.0       0.81      0.36      0.50        36
         1.0       0.73      0.95      0.82        64

    accuracy                           0.74       100
   macro avg       0.77      0.66      0.66       100
weighted avg       0.76      0.74      0.71       100

